"""change dream model column to string

Revision ID: 6183ca15632d
Revises: f6b611267d93
Create Date: 2025-01-07 14:09:10.759146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6183ca15632d'
down_revision = 'f6b611267d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=1200),
               type_=sa.String(length=1200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1200),
               type_=sa.TEXT(length=1200),
               existing_nullable=False)

    # ### end Alembic commands ###
